### ISSUE TITLE
metrics-graphite-3.1.3: GraphiteUDP reporter throws exception

### ISSUE THREAD

**Issue by cbring** [dropwizard/metrics#1100]
When using the metrics-graphite-3.1.3 GraphiteUDP implementation the reporter throws IllegalStateException upon each report except for the first invocation.

`ERROR  com.codahale.metrics.ScheduledReporter - Exception thrown from GraphiteReporter#report. Exception was suppressed.
java.lang.IllegalStateException: Already connected
	at com.codahale.metrics.graphite.GraphiteUDP.connect(GraphiteUDP.java:53)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:166)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by arteam** [comment]
Oh, right! Thanks for reporting this. I actually fixed this with #1080, but it was merged only to 3.2.0. I forgot that `GraphiteReporter` now invokes `connect` before `send`. I will release 3.1.4 shortly.

**Comment by arteam** [comment]
I've released dropwizard-metrics 3.1.4 to the Maven central repository. Should be available in a couple of hours.

**Comment by cbring** [comment]
Thanks for the speedy fix!
