### ISSUE TITLE
ArrayIndexOutOfBoundsException in UniformSnapshot constructor

### ISSUE THREAD

**Issue by markus-s24** [dropwizard/metrics#1104]
When constructing a UniformSnapshot, the passed in collection of values seems to get modified asynchronously. After the construction of the new value array and before the iteration of the collection, elements seem to get added, resulting in the array being to small.

In my opinion there needs to be some synchronization in SlidingTimeWindowReservoir when getting the collection of values, because there is no other way to get a clean copy of the collection. 

An alternative would be to use a list instead of an array in UniformSnapshot for the values, because due to dynamic sizing this issue won't occur.

Stacktrace:
```
java.lang.ArrayIndexOutOfBoundsException: 26591
        at com.codahale.metrics.UniformSnapshot.<init>(UniformSnapshot.java:29) ~[metrics-core-3.2.0.jar:3.2.0]
        at com.codahale.metrics.SlidingTimeWindowReservoir.getSnapshot(SlidingTimeWindowReservoir.java:67) ~[metrics-core-3.2.0.jar:3.2.0]
        at com.codahale.metrics.Histogram.getSnapshot(Histogram.java:54) ~[metrics-core-3.2.0.jar:3.2.0]
        at com.codahale.metrics.Timer.getSnapshot(Timer.java:159) ~[metrics-core-3.2.0.jar:3.2.0]
        at com.codahale.metrics.graphite.GraphiteReporter.reportTimer(GraphiteReporter.java:287) ~[metrics-graphite-3.2.0.jar:3.2.0]
        at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:259) ~[metrics-graphite-3.2.0.jar:3.2.0]
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:251) ~[metrics-core-3.2.0.jar:3.2.0]
        at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:174) [metrics-core-3.2.0.jar:3.2.0]
```

**Comment by arteam** [comment]
Thanks for the bug report! I think we could add a guard condition to the copy loop as an immediate fix for the race condition:

```java
for (Long value : values) {
            if (i >= size) {
                break;
            }
            this.values[i++] = value;
        }
```

But this doesn't fix the root cause. Does this error happen only in the 3.2.0 version? I wonder if #1063 could cause it.

**Comment by markus-s24** [comment]
I noticed the problem with 3.2.0, but I am not sure whether it happened before with earlier versions.

I took a short look at #1063 but found no reason, why it can cause this problem, because it just shortens the measurements map.
