### ISSUE TITLE
GraphiteReporter + PickledGraphite - IllegalStateException "Already connected"

### ISSUE THREAD

**Issue by steve-oakey** [dropwizard/metrics#1122]
Using version 3.2.2, I am getting these exceptions about every 5 minutes. My reporting rate is every minute, so I receive this error regularly every 5th minute. Any ideas what may be happening? I don't see any errors indicating that the call to `graphite.close()` failed in the `GraphiteReporter` or that closing the `PickledGraphite` writer and socket failed.

**Comment by osigida** [comment]
@steve-oakey a stack trace would help...

**Comment by steve-oakey** [comment]
I'm on an air-gapped network so here is a paraphrased stack trace. Not sure how much help this will be.

```
java.lang.IllegalStateException: Already connected
  at PickledGraphite.connect(PickledGraphite:173)
  at GraphiteReporter.report(GraphiteReporter:240)
  at ScheduledReporter.report(ScheduledReporter:251)
  at ScheduledReporter$1.run(ScheduledReporter:174)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors:511)
  at java.util.concurrent ....
  at java.util.concurrent ....
```

I'm using the default Executor so it is a single thread scheduled executor.

**Comment by arteam** [comment]
That's very strange. My first guess is that calls to GraphiteReporter#report intersect in some way and cause one of them to fail. It would be really great to have a reproducer, but other debug information would be helpful too.

**Comment by mazorigal** [comment]
Hi,

@arteam 
I recently migrated also to 3.2.2 and having similar issue:

```
23:03:05.438 ERROR c.codahale.metrics.ScheduledReporter  - Exception thrown from GraphiteReporter#report. Exception was suppressed.
java.lang.IllegalStateException: Already connected
	at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:111)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:240)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:251)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
could it related somehow to that:
https://github.com/dropwizard/metrics/issues/1100 ?
