### ISSUE TITLE
com.codahale.metrics.JmxAttributeGauge exception

### ISSUE THREAD

**Issue by RosenZhang** [dropwizard/metrics#1143]
Hi I have encountered this problem when I was trying to start a Spring boot application. Being searching for some time, still no idea how to solve it :(

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'UIDevServer' defined in class path resource [com/server/config/LocalConfig.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.<init>(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;Ljava/lang/String;)V
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at com.server.SpringBootApp$.delayedEndpoint$com$server$SpringBootApp$1(Main.scala:49)
	at com.server.SpringBootApp$delayedInit$body.apply(Main.scala:46)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.server.SpringBootApp$.main(Main.scala:46)
	at com.server.SpringBootApp.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.<init>(Ljavax/management/MBeanServerConnection;Ljavax/management/ObjectName;Ljava/lang/String;)V
	at com.codahale.metrics.jvm.BufferPoolMetricSet.getMetrics(BufferPoolMetricSet.java:45)
	at com.codahale.metrics.MetricRegistry.registerAll(MetricRegistry.java:381)
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:85)
	at ops.gateway.bootstrap.server.OpsServer$$anonfun$buildServer$1.apply(OpsServer.scala:160)
	at ops.gateway.bootstrap.server.OpsServer$$anonfun$buildServer$1.apply(OpsServer.scala:160)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:48)
	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:47)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at ops.gateway.bootstrap.server.OpsServer$class.buildServer(OpsServer.scala:159)
	at ops.gateway.bootstrap.server.OpsServer$class.run(OpsServer.scala:140)
	at com.server.UIServer.run(Main.scala:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 29 common frames omitted

```

**Comment by ChetWang** [comment]
java.lang.NoSuchMethodError: com.codahale.metrics.JmxAttributeGauge.

I think it may have some metrics jars confiliction

**Comment by arteam** [comment]
Looks like so. I think commit 0609cc695f486af5482b132ab89aeab392e88f82 could be a culprit. It was introduced in metrics 3.0.2. @RosenZhang, please check that your metrics version is equal or higher than it.
