### ISSUE TITLE
Under Java 8 version 161 

### ISSUE THREAD

**Issue by Narimm** [dropwizard/metrics#1293]
com.codahale.metrics.collectd.PacketWriterTest.testEncryptRequest

This test fails due to  change in the manner in which hava handles RSA generation..

we initially changed to explicitly declar the key size so when recieving the packet we knew its size
```
KeyPairGenerator gen = KeyPairGenerator.getInstance("RSA");
gen.initialize(1024);
```
// As of Java 1.8.161 the default RSA key was 2048 not 1024 -

```
java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at com.codahale.metrics.collectd.PacketWriter.encrypt(PacketWriter.java:220)
	at com.codahale.metrics.collectd.PacketWriter.encryptPacket(PacketWriter.java:193)
	at com.codahale.metrics.collectd.PacketWriter.write(PacketWriter.java:84)
	at com.codahale.metrics.collectd.PacketWriterTest.testEncryptRequest(PacketWriterTest.java:137)
```

**Comment by arteam** [comment]
Thanks for the report! It's very strange that AES encryption fails because of a wrong key size for public-key cryptography. Could you provide a unit test that fails on JDK Java 1.8.161? We run the tests on Travis CI on Oracle JDK 1.8.0_161 and they seem to pass.

**Comment by Narimm** [comment]
I will take a look sure

**Comment by Narimm** [comment]
So I have verified this is not an issue as long as you build against a JDK  > 1.8.161 ...do you still want to put in a unit test .

**Comment by Narimm** [comment]
It does mean metrics using a collectd ssl connection may fail on Java 1.8.152 or less

**Comment by arteam** [comment]
Sure, I it would be nice to have a such unit test! Anybody can then test the Collectd reporter for earlier JDK versions, and maybe submit a fix.
