### ISSUE TITLE
Getting ConnectException, even if we do have data being pushed

### ISSUE THREAD

**Issue by alexandru** [dropwizard/metrics#1491]
Using Dropwizard Metrics `4.1.0` with an initialized reporter like this:

```scala
val pickledGraphite = new PickledGraphite(new InetSocketAddress(config.graphite.host, 2004))
val graphiteReporter = GraphiteReporter
  .forRegistry(registry)
  .prefixedWith(prefix)
  .convertRatesTo(TimeUnit.SECONDS)
  .convertDurationsTo(TimeUnit.MILLISECONDS)
  .filter(MetricFilter.ALL)
  .build(pickledGraphite)

graphiteReporter.start(30, TimeUnit.SECONDS)
```

We are getting this periodic exception, even if we do get the data in Graphite, so this is weird:

```
java.net.ConnectException: Operation timed out (Connection timed out)
    at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at java.net.Socket.<init>(Socket.java:434)
    at java.net.Socket.<init>(Socket.java:244)
    at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:277)
    at com.codahale.metrics.graphite.PickledGraphite.connect(PickledGraphite.java:185)
    at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:265)
    at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:237)
    at com.codahale.metrics.ScheduledReporter.lambda$start$0(ScheduledReporter.java:177)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

We changed the Graphite server to a new setup, but same version; with the old server it wasn't misbehaving, so there's something about our server. 

The problem is that from my calculations, this error happens every time the reporter tries to send a report. Yet we can see data in Graphite, so clearly the connection was successful and the data is received.

Any ideas why this error happens?

**Comment by alexandru** [comment]
Spotted problems on our end. Please ignore. Thanks.
