### ISSUE TITLE
Graphite flush is failed on writing to socket 

### ISSUE THREAD

**Issue by vipinkumar7** [dropwizard/metrics#1494]
I am getting this exception write failed .I am checking for isConnected()  before and then doing send and flush 

> java.net.SocketException: Connection timed out (Write failed)
> 	at java.net.SocketOutputStream.socketWrite0(Native Method)
> 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
> 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
> 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
> 	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
> 	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
> 	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
> 	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
> 	at java.io.BufferedWriter.flush(BufferedWriter.java:254)
> 	at com.codahale.metrics.graphite.Graphite.flush(Graphite.java:161)
> 	at com.walmart.rum.pools.GraphiteConnection.flush(GraphiteConnection.scala:94)

**Comment by vipinkumar7** [comment]
Timeout configuration can't be passed to Socket object in Graphite.java
