### ISSUE TITLE
NoClassDefFoundError on loading com/sun/management/UnixOperatingSystemMXBean

### ISSUE THREAD

**Issue by sammyhk** [dropwizard/metrics#1519]
We got `NoClassDefFoundError` on loading `com/sun/management/UnixOperatingSystemMXBean`  when accessing `FileDescriptorRatioGauge` on OpenJDK8 OpenJ9 build, suspected
https://github.com/dropwizard/metrics/blob/9438c91679eba570e3a7fa1aa43a82801af7a33f/metrics-jvm/src/main/java/com/codahale/metrics/jvm/FileDescriptorRatioGauge.java#L33
using Sun/Oracle internal class which should only works on Oracle/ HotSpot JDK. Suggest to check class accessibility before type casting.

Stacktrace:
```
java.lang.NoClassDefFoundError: com/sun/management/UnixOperatingSystemMXBean
	at com.codahale.metrics.jvm.FileDescriptorRatioGauge.getRatio(FileDescriptorRatioGauge.java:33)
	at com.codahale.metrics.RatioGauge.getValue(RatioGauge.java:64)
	at com.codahale.metrics.RatioGauge.getValue(RatioGauge.java:11)
	at com.codahale.metrics.json.MetricsModule$GaugeSerializer.serialize(MetricsModule.java:42)
	at com.codahale.metrics.json.MetricsModule$GaugeSerializer.serialize(MetricsModule.java:26)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2795)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1769)
	at com.codahale.metrics.json.MetricsModule$MetricRegistrySerializer.serialize(MetricsModule.java:210)
	at com.codahale.metrics.json.MetricsModule$MetricRegistrySerializer.serialize(MetricsModule.java:193)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1135)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:960)
	at com.codahale.metrics.servlets.MetricsServlet.doGet(MetricsServlet.java:179)
        ...
```

**Comment by emil-edholm-wcar** [comment]
I have the same issue but I'm running OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS) which I think has HotSpot?

**Comment by joschi** [comment]
@sammyhk @emil-edholm-wcar Thanks for reporting this!

Would one of you be able to provide a PR to fix this issue?
