### ISSUE TITLE
Standalone metrics-healthchecks use crashes, due to Clock dependency

### ISSUE THREAD

**Issue by tingley** [dropwizard/metrics#1966]
Since version 4.1.0, it's been impossible to include the metrics-healthchecks library as a standalone dependency, due to an unresolved class error for `com.codahale.metrics.Clock`:

```
java.lang.NoClassDefFoundError: com/codahale/metrics/Clock
	at com.codahale.metrics.health.HealthCheck.clock(HealthCheck.java:383) ~[metrics-healthchecks-4.2.0.jar:4.2.0]
	at com.codahale.metrics.health.HealthCheck.execute(HealthCheck.java:371) ~[metrics-healthchecks-4.2.0.jar:4.2.0]
	at com.codahale.metrics.health.HealthCheckRegistry.runHealthChecks(HealthCheckRegistry.java:184) ~[metrics-healthchecks-4.2.0.jar:4.2.0]
	at com.codahale.metrics.health.HealthCheckRegistry.runHealthChecks(HealthCheckRegistry.java:169) ~[metrics-healthchecks-4.2.0.jar:4.2.0]
      [... calling code ...]
```

I am fairly sure this is a result of #1372.

The simplest fix would simply be to list `metrics-core` as a dependency.

**Comment by tingley** [comment]
@joschi Thanks for the quick fix!
