### ISSUE TITLE
AbstractMethodError on HEAD

### ISSUE THREAD

**Issue by francois** [dropwizard/metrics#78]
Perhaps related to 606249bbee6cee94e5366cece4183e2965ff34a5, but my app doesn't start correctly anymore. I get failures when instantiating my objects. I'm not using the feature in this commit myself, so I can't evaluate it's usefulness.

```
Exception in thread "main" java.lang.AbstractMethodError:     seevibes.twitter.Converter.metricsRegistry()Lcom/yammer/metrics/core/MetricsRegistry;
    at com.yammer.metrics.Instrumented$class.com$yammer$metrics$Instrumented$$metricsGroup(Instrumented.scala:7)
    at seevibes.twitter.Converter.com$yammer$metrics$Instrumented$$metricsGroup(Converter.scala:21)
    at com.yammer.metrics.Instrumented$class.metrics(Instrumented.scala:12)
    at seevibes.twitter.Converter.metrics(Converter.scala:21)
```

I'll try without this commit tomorrow.

**Comment by timmolter** [comment]
I had this issue too, but a different class. It was a dependency version conflict.
